service: save-to-pocket-bot-lambda

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  stage: prod
  region: eu-central-1

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  bot:
    handler: bin/savetopocketbot
    events:
      - http:
          path: /
          method: any
    memorySize: 128
    timeout: 3
    reservedConcurrency: 1
    environment:
      TG_TOKEN: ${file(config.${self:provider.stage}.json):tg-token}
      POCKET_CONSUMER_KEY: ${file(config.${self:provider.stage}.json):pocket-consumer-key}
      POCKET_TOKEN_TABLE: ${file(config.${self:provider.stage}.json):pocket-token-table}
      TG_REDIRECT_URL: ${file(config.${self:provider.stage}.json):tg-redirect-url}